```{r data generation, echo = FALSE, results = 'hide'}
a = sample(5:9, size = 1)
b = sample(1:7, size = 1)
```

Question
========
Рассмотрим одновременную игру в которую играют `r a` игроков, у каждого из которых конечное число стратегий. 

Что может произойти с количеством равновесий Нэша в чистых стратегиях, $n_{NE}$, и количеством Парето-оптимальных исходов в чистых стратегиях, $n_{PO}$,
при увеличении выигрыша первого игрока на `r b` во всех исходах?

Answerlist
----------
*  $n_{NE}$ не изменится, $n_{PO}$ может измениться в любую сторону
*  $n_{NE}$ может измениться в любую сторону, $n_{PO}$ может только вырасти
*  $n_{NE}$ и $n_{PO}$ могут измениться в любую сторону
*  $n_{NE}$ может только вырасти, $n_{PO}$ может только упасть
*  $n_{NE}$ может только вырасти, $n_{PO}$ не изменится
*  нет верного ответа


Solution
========


Meta-information
================
exname: wind of changes
extype: schoice
exsolution: 100000
exshuffle: 6
exextra[Type]: Calculation
exextra[Language]: Russian
exsection: ...
